# Intermediate Python - Week 1

Welcome to the Intermediate Python course!

We will be focussing on getting familiar with Python using examples that you might come across in your day-to-day work.
During this course, you will get familiar with Python for automating data analysis, creating publication-quality graphics,
and we will touch upon machine learning.  We are assuming you are somewhat familiar with Python (or another object-oriented-language),
since we will not cover the basics of syntax and login in as much detail as the beginner course.

The course will be taught primarily through Jupyter notebooks, although it will take the form of an initial introduction from us,
followed by plenty of problem-solving with help from us when required

We will use individual break out rooms to talk through specific problems with one of us.
There will be plenty of content in the notebooks, which you should work through at your own pace during the workshop
sessions.  Anything left over can be completed as homework before the next session.

## Goals for Week 1
_____
* Understand Python's library of external packages
* Introduction to environments and package management
* Gentle introduction to numpy

### Expanding on the standard library: packages, package managers and environments
_____

Python, like many languages, has an extensive library of modules - packaged up python code - that extend it's basic functionality and allows you to use python for many task-specific things without having to reinvent the wheel.  We will make extensive use of these packages in the coming weeks.

We can install external packages using a package manager like `pip` or `conda`, e.g. `pip install numpy` will, by default, install the latest version of numpy it can find.

You can imagine that having lots of packages available to the system python interpreter could get messy! What if two packages require a different version of numpy?

To solve this problem we create isolated environments, where the python interpreter can only access certain packages that we control.  This will be crucial in a few weeks when we start to explore writing your own standaline programs outside of a jupyter notebook.



### A worked useful of external packages - Introduction to NumPy and matplotlib

NumPy (Numerical Python) is Python's <i> de facto <i/> linear algebra package - it provides support for working and operating on matrices.  It introduces the array datatype and associated linear algebra methods for fast matrix computation - think list of lists but much faster!

Let's get some practice with the basics of NumPy and handling array data

In [1]:
import numpy as np

A fundamental (but often overlooked) component of writing code is writing useful documentation that goes along with it - all of the modules we will be using have thorough documentation that describes what each function does, the expected arguments, what it will return and in most cases an example, e.g....

In [2]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

We can initialise an array object in a few ways:
* `a = np.arange(5)` 1D array of 20 consecutive elements i.e. np.array([0,1,2,3,4])
* using `np.linspace()`
* passing list objects to `np.array()` which can be converted into an array (use nested lists for multi-dimentional lists).
* Initialising an array of arbitrary dimensions where each element is the same  - `np.zeros()`, `np.ones()`


In [8]:
# create a 1D array with 20 elements using np.arange()
# ------------------------------------
a = np.arange(15)

# now use the array's reshape method to reshape your array to have dimensions 4x5
# ------------------------------------
b = a.reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
# Another way to initialise arrays is from nested lists. Create a 3x3 array from lists:
# Create a 3x4 array using list initialisation
# ------------------------------------



We can inspect some properties of the arrays we've created, using methods of the array class

In [13]:
# print the shape of the array using the array's `shape` method
# ------------------------------------

# print the array's datatype using Python's built-in `type` function
# ------------------------------------

# get the internal datatype the array is storing by accessing the name attribute of the array's `dtype` ie array.dtype.name


(20,)
<class 'numpy.ndarray'>
int64


#### Fundamental operations on arrays

Now that we know a few ways to initialise arrays, we can think about the operations we can perform on them - in general, we can perform any mathematically valid operation on an array.

In [9]:
# define two matrices of the same size and add them together
# ------------------------------------

# add an integer, elementwise, to the array
# ------------------------------------


array([ 7,  9, 11, 13, 15])

In [10]:
# define a matrix and apply the sinusoid function to it.  Then print the elementwise square of the result
# ------------------------------------


array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [28]:
# Now some linear algebra
a = np.full((2,3), 2)
b = np.random.random((3,5))
print(a)
print(b)
c = np.matmul(a,b)
c

# calculate the detminant of a matrix

c = np.identity(3)

det = np.linalg.det(c)
det

[[2 2 2]
 [2 2 2]]
[[0.97359209 0.31567806 0.33294839 0.0373183  0.32544297]
 [0.45715937 0.66729532 0.41529075 0.04081766 0.36436942]
 [0.2254244  0.54170689 0.80640768 0.06205257 0.44744193]]


1.0

### Indexing, slicing and iterating over matrices

* A one dimensional array can be iterated over in the same way as you could for a regular list object.
* Indexing and slicing follows a familiar syntax as lists too


In [17]:
# create a one dimentional matrix of at least 10 elements, iterate over it using a `for` loop, printing each value in turn
# ------------------------------------
a = np.arange(10)
for i in a:
    print(i)

# now retrieve the 2nd element of the array same syntax as indexing a list
# ------------------------------------


# print all elements from the 3rd to the end
# ------------------------------------


0
1
2
3
4
5
6
7
8
9


 1
[3 4 5 6 7 8 9]


In [38]:
# what happens when we try the same things with a two dimensional array?
# Initialise one using any appropriate method from above, 
# ------------------------------------


# By convention, indexing of 2d arrays is done as [rows, cols]
# ------------------------------------


# now try iterating over it using the same construct as before, print the result.  Is this what you expected?
# ------------------------------------



[[ 8  9]
 [13 14]]


In [27]:
# If you want to iterate over each element of the matrix, you need to iterate over the .flat attribute of the array object.  See if you can print each individual element of the array you created above.
# ------------------------------------



Now it's your turn! In the code cell below, see if you can produce the following matrix without writing it out manually!

| 1 | 1 | 1 | 1 | 1 |
|---|---|---|---|---|
| 1 | 0 | 0 | 0 | 1 |
| 1 | 0 | 1 | 0 | 0 |
| 1 | 0 | 0 | 0 | 1 |
| 1 | 1 | 1 | 1 | 1 |


now see if you can initialise the following matrix and retrieve the parts that have been highlighted?

### Concatenating arrays

Numpy provides a few ways to concatenate arrays

In [10]:
# Concatenate arrays into a single dimention
a1 = np.arange(4).reshape(2,2)
b1 = np.array([5,6])



In [9]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

d = np.vstack((a,b))
d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])